# v1_deployment_config.yml
---

- create:
    name: frontend
    namespace: k8s-project
    pod_metadata_labels:
      name: frontend
    pod_containers:
    - name: helloworld
      image: openshift/origin-ruby-sample
      ports:
      - container_port: 8080
        protocol: TCP
        name: http-port
    replicas: 5
    selector:
      name: frontend
    triggers:
    - type: ConfigChange
    - type: ImageChange
      image_change_params:
        automatic: true
        container_names:
        - helloworld
        _from:
          kind: ImageStreamTag
          name: "origin-ruby-sample:latest"
    deployment_strategy_type: Rolling
  name: Create deployment config

- patch:
    name: frontend
    namespace: k8s-project
    pod_metadata_labels:
      name: frontend
    pod_containers:
    - name: helloworld
      image: "openshift/origin-ruby-sample:v1.0"
      ports:
      - container_port: 9000
        protocol: UDP
        name: udp-port
    replicas: 3
  name: Patch deployment config

- replace:
    name: frontend
    namespace: k8s-project
    pod_metadata_labels:
      name: frontend_app
    pod_containers:
    - name: helloworld
      image: openshift/origin-ruby-sample:v2
      ports:
      - container_port: 8888
        protocol: TCP
        name: http-port
    replicas: 2
    selector:
      name: frontend_app
    triggers:
    - type: ConfigChange
    - type: ImageChange
      image_change_params:
        automatic: true
        container_names:
        - helloworld
        _from:
          kind: ImageStreamTag
          name: "origin-ruby-sample:v2"
    deployment_strategy_type: Rolling
  name: Replace deployment config

- remove:
    name: frontend
    namespace: k8s-project
  name: Remove deployment config
